expansion/urls.py
# _*_ encoding:utf-8 _*_
from django.conf.urls import url, include
from rest_framework import routers

from expansion import views


router = routers.DefaultRouter()
router.register(r'kks', views.KksViewset)
router.register(r'value', views.MeasureValueViewset)

# 此处（?P<>）格式标记参数名称
urlpatterns = [
    url(r'^f5/', views.f5_ajax, name='f5'),
    url(r'^query_vector', views.query_vector, name='query_vector'),
    url(r'^query_ab', views.query_ab, name='query_ab'),
    url(r'^query_rate', views.query_rate, name='query_rate'),
    url(r'^funview/', views.funview),
    url(r'^addview/', views.addview, name='add'),
    url(r'^addview2/(\d+)/(\d+)', views.add_redirect),
    url(r'^new_add/(\d+)/(\d+)', views.addview2, name='add2'),
    url(r'^', include(router.urls)),
    url(r'api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

gastempdisplay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from xadmin.plugins import xversion
import xadmin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', include(xadmin.site.urls), name='xadmin'),
    url(r'^index/', TemplateView.as_view(template_name='index.html'), name='homepage'),
    url(r'^siderbar/', TemplateView.as_view(template_name='gasmonitor.html'), name='siderbar'),
    url(r'^waterwall/', include('waterwall.urls', namespace='waterwall')),
    url(r'^expansion/', include('expansion.urls', namespace='expansion')),
    url(r'^bootstrap/', TemplateView.as_view(template_name='expansionbase.html'))
]

waterwall/urls.py
# _*_ encoding:utf-8 _*_
from django.conf.urls import url
from .views import ExpansionView

urlpatterns = [
    url(r'^expansion/', ExpansionView.as_view(), name='expansion'),
]

xadmin/views/base.py
import sys
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.utils.encoding import force_unicode, force_text
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_unicode, smart_unicode, smart_str
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, basestring) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_unicode(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

    def init_request(self, *args, **kwargs):
        pass

    def init_plugin(self, *args, **kwargs):
        plugins = []
        for p in self.base_plugins:
            p.request = self.request

templates/exbasecopy.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    {% csrf_token %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/modern-business.css' %}">

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/d3.V4.min.js' %}"></script>

    <script src="{% static 'js/monitorpage.js' %}"></script>
    <script src="{% static 'js/screen.js' %}"></script>

    <style>
        svg {
{#            background-color:  whitesmoke;#}
            border: 1px solid whitesmoke;
        }
    </style>

    <title>Title</title>
</head>
<body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">
              <img alt="Brand" src="{% static 'images/brand.png' %}">
          </a>
            <a class="navbar-brand" href="#">
              WSH
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="#">启动 <span class="sr-only">(current)</span></a></li>
            <li><a href="#">偏差</a></li>
            <li><a href="#">报警 <span class="badge">4</span></a></li>
            <li><a href="#">后台</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-7">
                <div class="row">
                    <h5 class="text-left">XY方向膨胀</h5>
                    <svg height="200" width="580" id="xy">
                        <!--<rect height="250" width="580" fill="green" opacity="0.5"></rect>-->
                    </svg>
                </div>
                <div class="row">
                    <h5 class="text-left">Z方向膨胀</h5>
                    <svg height="200" width="580" id="z">
                    </svg>
                </div>
            </div>
            <div class="col-md-5">
                <h5 class="text-left">左右侧膨胀比例</h5>
                <svg height="440" width="420" id="rl">
                </svg>
            </div>
        </div>

        <div class="row">
            <h5 class="text-left">各方向膨胀变化率</h5>
            <svg height="150" width="1007" id="rate">

            </svg>
        </div>
    </div>

    <!-- 测试ajax -->
    <script>
{#        query_vector数据用以绘制xyz散点图及z方向柱状图#}
{#        query_ab数据用以绘制左右侧偏差曲线图#}
        var query_vector = [];
        var query_ab = [];
        var query_rate =[];

        function get_ab() {
            $.getJSON('{% url 'expansion:query_ab' %}', function(ret){
                fig_rl(ret);
                query_ab = ret;
                return query_ab;
            })
        }

        function get_vector() {
            $.getJSON('{% url 'expansion:query_vector' %}',function(ret){
                fig_xy(ret);
                fig_z(ret);
                query_vector = ret;
                return query_vector;
            })
        }

        function get_rate() {
            $.getJSON('{% url 'expansion:query_rate' %}',function(ret){
                fig_rate(ret)
                query_rate = ret;
                return query_rate;
            })
        }

        $(document).ready(function () {
            get_vector();
            get_ab();
            get_rate();
            setInterval(get_vector, 3000);
            setInterval(get_ab, 3000);
            setInterval(get_rate,3000);
        });

    </script>

    <script>
    function fig_xy(data) {
        var newsvg = d3.select('#xy');

        var width = newsvg.attr('width');
        var height = newsvg.attr('height');
        var padding = {'left':30,'right':20,'top':20,'bottom':30};

        var xscale = d3.scaleLinear()
            .domain([0,1])
            .range([padding.left,width-padding.right]);

        var yscale = d3.scaleLinear()
            .domain([0,1])
            .range([height-padding.bottom,padding.top]);

        var svgupdate = newsvg.selectAll('circle')
            .data(data);

        var svgenter = svgupdate.enter();

        var svgexit = svgupdate.exit();

        svgupdate
            .attr('cx',function (d,i) {
                return xscale(parseFloat(d.x))
            })
            .attr('cy',function (d,i) {
                return yscale(parseFloat(d.y))
            })
            .attr('r',10)
            .attr('fill','green')
            .attr('opacity',0.5)
            ;

        svgenter.append('circle')
            .attr('cx',function (d,i) {
                return xscale(d.x)
            })
            .attr('cy',function (d,i) {
                return yscale(d.y)
            })
            .attr('r',10)
            .attr('fill','green')
            .attr('opacity',0.5);

        svgexit.remove();
    }

    function fig_rl(data) {
        var svgrl = d3.select('#rl');

        var width = svgrl.attr('width');
        var height = svgrl.attr('height');
        var padding = {'left': 30, 'right': 20, 'top': 20, 'bottom': 10};

        var xscale = d3.scaleLog()
            .domain([0.5, 2])
            .range([padding.left, width - padding.right]);

        var yscale = d3.scaleLinear()
            .domain([0, data.length-1])
            .range([padding.top,height - padding.bottom]);


        var linePath = d3.line()
            .x(function (d,i) {
                return xscale(d[0])
            })
            .y(function (d,i) {
                return yscale(d[1])
            })
                .curve(d3.curveCardinal)
            ;

        var xlinePath = d3.line()
            .x(function (d,i) {
                return xscale(
                    parseFloat(d.right.x)/parseFloat(d.left.x)
                )
            })
            .y(function (d,i) {
                return yscale(i)
            })
            .curve(d3.curveCardinal);

        var ylinePath = d3.line()
            .x(function (d,i) {
                return xscale(
                    parseFloat(d.right.y)/parseFloat(d.left.y)
                )
            })
            .y(function (d,i) {
                return yscale(i)
            })
            .curve(d3.curveCardinal);

        var zlinePath = d3.line()
            .x(function (d,i) {
                return xscale(
                    parseFloat(d.right.z)/parseFloat(d.left.z)
                )
            })
            .y(function (d,i) {
                return yscale(i)
            })
            .curve(d3.curveCardinal);

        function draw(lpath, color, sym, vector) {
            var svgupdate = svgrl.selectAll('#path'+vector).data([1]);
            var svgenter = svgupdate.enter();
            var svgexit = svgupdate.exit();

            var symupdate = svgrl.selectAll('#sym'+vector)
                .data(data);

            var symenter = symupdate.enter();

            var symexit = symupdate.exit();

            svgupdate
                .attr('d', lpath(data))
                .attr('id','path'+vector)
                .attr('stroke', color)
                .attr('stroke-width', '1.5')
                .attr('fill', 'none')
                .attr('opacity',0.8);

            svgenter.append('path')
                .attr('d', lpath(data))
                .attr('id','path'+vector)
                .attr('stroke', color)
                .attr('stroke-width', '1.5')
                .attr('fill', 'none')
                .attr('opacity',0.8);

            svgexit.remove();

            symupdate
                .attr('id','sym'+vector)
                .attr('transform',function (d,i) {
                    return 'translate('+xscale(parseFloat(d.right[vector])/parseFloat(d.left[vector]))+','+yscale(i)+')'
                })
                .attr('d',d3.symbol().type(function (d,i) {
                    return d3.symbols[sym];
                }).size(50))
                .style('fill',color)
                .attr('opacity',0.8);

            symenter
                    .append('path')
                    .attr('id','sym'+vector)
                    .attr('transform',function (d,i) {
                        return 'translate('+xscale(parseFloat(d.right[vector])/parseFloat(d.left[vector]))+','+yscale(i)+')'
                    })
                    .attr('d',d3.symbol().type(function (d,i) {
                        return d3.symbols[sym];
                    }).size(50))
                    .style('fill',color)
                    .attr('opacity',0.8);

            symexit.remove();
        }

        draw(xlinePath,'red',1,'x');
        draw(ylinePath,'green',2,'y');
        draw(zlinePath,'orange',3,'z');

        svgrl.append('path')
            .attr('d',linePath([[1,0],[1,data.length-1]]))
            .attr('stroke','black')
            .attr('stroke-width','1')
            .attr('stroke-dasharray','5 2');


    }

    function fig_z(data) {
        var svgz = d3.select('#z');

        var width = svgz.attr('width');
        var height = svgz.attr('height');
        var padding = {'left':10,'right':10,'top':25,'bottom':5};

{#        var xscale = d3.scaleLinear()#}
{#            .domain([0,1])#}
{#            .range([padding.left,width-padding.right]);#}
        var rectpad = width/data.length;

        var rectwidth = rectpad/1.2;

        var padwidth = rectpad/12;

        var yscale = d3.scaleLinear()
            .domain([0,1.5])
            .range([padding.top,height-padding.bottom]);

        var svgupdate = svgz.selectAll('rect')
            .data(data);

        var svgenter = svgupdate.enter();

        var svgexit = svgupdate.exit();

        svgupdate.attr('x',function (d,i) {
                return padwidth/2+i*rectpad
            })
            .attr('y',function (d,i) {
                return padding.top
            })
            .attr('width',rectwidth)
            .attr('height',function (d,i) {
                return yscale(parseFloat(d.z))
            })
            .attr('fill','orange')
            .attr('opacity',0.8);

        svgenter.append('rect')
            .attr('x',function (d,i) {
                return padwidth/2+i*rectpad
            })
            .attr('y',function (d,i) {
                return padding.top
            })
            .attr('width',rectwidth)
            .attr('height',function (d,i) {
                return yscale(parseFloat(d.z))
            })
            .attr('fill','orange')
            .attr('opacity',0.8);

        svgexit.remove();

    }

    function fig_rate(data) {
        var svg = d3.select('#rate');

        var width = svg.attr('width');
        var height = svg.attr('height');
        var padding = {'left':10,'right':10,'top':5,'bottom':5};

        var color = {'x':'red','y':'green','z':'orange'};

        var rectpad = width/data.length*3;

        var rectwidth = rectpad/4;

        var padwidth = rectpad/4;


        var uplimit = 0.2;
        var dnlimit =-0.2;
        var yscale = d3.scaleLinear()
            .domain([dnlimit,uplimit])
            .range([height-padding.bottom,padding.top]);

        var svgupdate = svg.selectAll('rect')
            .data(data);

        var svgenter = svgupdate.enter();

        var svgexit = svgupdate.exit();

        svgupdate.attr('x',function (d,i) {
                return padwidth/2+(i%3)*rectwidth+parseInt(i/3)*rectpad
            })
            .attr('y',function (d,i) {
                r = parseFloat(d.now.value)-parseFloat(d.before.value);
                if (r>=0){
                    return yscale(r);
                }else {
                    return yscale(0);
                }
            })
            .attr('width',rectwidth)
            .attr('height',function (d,i) {
                r = parseFloat(d.now.value)-parseFloat(d.before.value);
                if (r>=0){
                    return yscale(0)-yscale(r)
                }else{
                    return yscale(r)-yscale(0)
                }
            })
            .attr('fill',function (d,i) {
                return color[d.kks__vector]
            })
            .attr('opacity',0.8);

        svgenter.append('rect')
            attr('x',function (d,i) {
                return padwidth/2+(i%3)*rectwidth+parseInt(i/3)*rectpad
            })
            .attr('y',function (d,i) {
                r = parseFloat(d.now.value)-parseFloat(d.before.value);
                if (r>=0){
                    return yscale(r);
                }else {
                    return yscale(0);
                }
            })
            .attr('width',rectwidth)
            .attr('height',function (d,i) {
                r = parseFloat(d.now.value)-parseFloat(d.before.value);
                if (r>=0){
                    return yscale(0)-yscale(r)
                }else{
                    return yscale(r)-yscale(0)
                }
            })
            .attr('fill',function (d,i) {
                return color[d.kks__vector]
            })
            .attr('opacity',0.8);

        svgexit.remove();
    }
    </script>


</body>


</html>

templates/gasmonitor.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block bread %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">烟温监测
                <small>高过出口</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{% url 'homepage' %}">Home</a>
                </li>
                <li >在线监测</li>
                <li class="active">烟温监测</li>
            </ol>
        </div>
    </div>
{% endblock bread %}

{% block leftnavi %}
    <div class="col-md-3">
                <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion"
                                href="#collapseOne">
                                在线监测
                                </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                            <div class="list-group">
                                <a href="{% url 'siderbar' %}" class="list-group-item active">烟温监测</a>
                                <a href="faq.html" class="list-group-item">壁温监测</a>
                                <a href="{% url 'waterwall:expansion' %}" class="list-group-item">膨胀监测</a>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion"
                                href="#collapseTwo">
                                状态检修
                            </a>
                            </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse">
                            <div class="list-group">
                                <a href="gasmonitor.html" class="list-group-item active">烟温监测</a>
                                <a href="faq.html" class="list-group-item">壁温监测</a>
                                <a href="404.html" class="list-group-item">膨胀监测</a>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion"
                                href="#collapseThree">
                                优化工况
                                </a>
                            </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse">
                            <div class="panel-body">
                                Nihil anim keffiyeh helvetica, craft beer labore wes anderson
                                cred nesciunt sapiente ea proident. Ad vegan excepteur butcher
                                vice lomo.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% endblock leftnavi %}

{% block content %}
    <div class="col-md-9">

                <svg width="700" height="400" stroke="#fff" stroke-width="0.5"></svg>

                <script>

                    // Populate a grid of n×m values where -2 ≤ x ≤ 2 and -2 ≤ y ≤ 1.
                    var n = 240, m = 125, values = new Array(n * m);
                    for (var j = 0.5, k = 0; j < m; ++j) {
                      for (var i = 0.5; i < n; ++i, ++k) {
                        values[k] = goldsteinPrice(i / n * 4 - 2, 1 - j / m * 3);
                      }
                    }

                    var svg = d3.select("svg"),
                        width = +svg.attr("width"),
                        height = +svg.attr("height");

                    var thresholds = d3.range(1, 21)
                        .map(function(p) { return Math.pow(2, p); });

                    var contours = d3.contours()
                        .size([n, m])
                        .thresholds(thresholds);

                    var color = d3.scaleLog()
                        .domain(d3.extent(thresholds))
                        .interpolate(function() { return d3.interpolateHclLong('orange','purple'); });

                    svg.selectAll("path")
                      .data(contours(values))
                      .enter().append("path")
                        .attr("d", d3.geoPath(d3.geoIdentity().scale(width / n)))
                        .attr("fill", function(d) { return color(d.value); });

                    // See https://en.wikipedia.org/wiki/Test_functions_for_optimization
                    function goldsteinPrice(x, y) {
                      return (1 + Math.pow(x + y + 1, 2) * (19 - 14 * x + 3 * x * x - 14 * y + 6 * x * x + 3 * y * y))
                          * (30 + Math.pow(2 * x - 3 * y, 2) * (18 - 32 * x + 12 * x * x + 48 * y - 36 * x * y + 27 * y * y));
                    }

                </script>
    </div>
{% endblock content %}